In [24]:
import pandas as pd
import numpy as np
import torch

In [25]:
from main import get_args

args = get_args()

In [26]:
data = pd.read_excel('./datasets/数据预处理.xlsx')
data.columns
data = data.drop(columns='case')
data = data.drop(columns='Unnamed: 5')
data = data.to_numpy()
data

array([[5.00000e-01, 5.00000e+00, 5.00000e-01, 5.00000e+00, 8.26530e+02,
        1.61000e+03],
       [1.00000e+00, 5.00000e+00, 1.00000e+00, 6.00000e+00, 1.68235e+03,
        3.94000e+03],
       [1.50000e+00, 5.00000e+00, 1.50000e+00, 7.00000e+00, 2.60000e+03,
        7.08000e+03],
       [2.00000e+00, 5.00000e+00, 2.00000e+00, 8.00000e+00, 3.40000e+03,
        1.08000e+04],
       [2.50000e+00, 5.00000e+00, 2.50000e+00, 9.00000e+00, 4.30000e+03,
        1.48000e+04],
       [3.00000e+00, 5.00000e+00, 3.00000e+00, 1.00000e+01, 5.00000e+03,
        1.93000e+04],
       [1.00000e+00, 6.00000e+00, 1.50000e+00, 5.00000e+00, 2.52450e+03,
        5.15000e+03],
       [5.00000e-01, 6.00000e+00, 2.00000e+00, 6.00000e+00, 1.70000e+03,
        4.95000e+03],
       [2.00000e+00, 6.00000e+00, 5.00000e-01, 7.00000e+00, 2.70000e+03,
        7.51000e+03],
       [1.50000e+00, 6.00000e+00, 1.00000e+00, 8.00000e+00, 2.20000e+03,
        7.18000e+03],
       [3.00000e+00, 6.00000e+00, 5.00000e-01, 9.0

In [27]:
X = data[:, :4]
Y = data[:, 4]

In [28]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X = scaler.fit_transform(X)


In [29]:
max_value = Y.max()

Y = Y / max_value
Y

array([0.165306, 0.33647 , 0.52    , 0.68    , 0.86    , 1.      ,
       0.5049  , 0.34    , 0.54    , 0.44    , 0.8     , 0.7     ,
       0.812156, 0.72    , 0.18    , 0.28    , 0.403334, 0.48    ,
       0.68    , 0.424082])

In [30]:
Y = Y.reshape(-1, 1)
Y

array([[0.165306],
       [0.33647 ],
       [0.52    ],
       [0.68    ],
       [0.86    ],
       [1.      ],
       [0.5049  ],
       [0.34    ],
       [0.54    ],
       [0.44    ],
       [0.8     ],
       [0.7     ],
       [0.812156],
       [0.72    ],
       [0.18    ],
       [0.28    ],
       [0.403334],
       [0.48    ],
       [0.68    ],
       [0.424082]])

In [31]:
tensor = np.concatenate([X, Y], axis = 1)
tensor

array([[0.        , 0.        , 0.        , 0.        , 0.165306  ],
       [0.2       , 0.        , 0.2       , 0.2       , 0.33647   ],
       [0.4       , 0.        , 0.4       , 0.4       , 0.52      ],
       [0.6       , 0.        , 0.6       , 0.6       , 0.68      ],
       [0.8       , 0.        , 0.8       , 0.8       , 0.86      ],
       [1.        , 0.        , 1.        , 1.        , 1.        ],
       [0.2       , 0.33333333, 0.4       , 0.        , 0.5049    ],
       [0.        , 0.33333333, 0.6       , 0.2       , 0.34      ],
       [0.6       , 0.33333333, 0.        , 0.4       , 0.54      ],
       [0.4       , 0.33333333, 0.2       , 0.6       , 0.44      ],
       [1.        , 0.33333333, 0.        , 0.8       , 0.8       ],
       [0.8       , 0.33333333, 0.2       , 1.        , 0.7       ],
       [0.4       , 0.66666667, 0.6       , 0.        , 0.812156  ],
       [0.6       , 0.66666667, 0.4       , 0.2       , 0.72      ],
       [0.        , 0.66666667, 0.

In [32]:
np.random.shuffle(tensor)
tensor

array([[1.        , 0.        , 1.        , 1.        , 1.        ],
       [0.        , 0.66666667, 1.        , 0.8       , 0.403334  ],
       [0.6       , 0.66666667, 0.4       , 0.2       , 0.72      ],
       [0.2       , 0.66666667, 0.8       , 1.        , 0.48      ],
       [0.8       , 0.        , 0.8       , 0.8       , 0.86      ],
       [0.6       , 0.        , 0.6       , 0.6       , 0.68      ],
       [0.4       , 0.        , 0.4       , 0.4       , 0.52      ],
       [0.8       , 0.33333333, 0.2       , 1.        , 0.7       ],
       [0.2       , 0.        , 0.2       , 0.2       , 0.33647   ],
       [0.2       , 0.33333333, 0.4       , 0.        , 0.5049    ],
       [0.        , 0.        , 0.        , 0.        , 0.165306  ],
       [0.6       , 1.        , 0.2       , 0.        , 0.68      ],
       [0.4       , 0.33333333, 0.2       , 0.6       , 0.44      ],
       [0.2       , 0.66666667, 0.        , 0.6       , 0.28      ],
       [0.        , 0.66666667, 0.

In [33]:
trainsize = int(len(tensor) * 0.80)
validsize = int(len(tensor) * 0.10)

In [34]:
train_tensor = tensor[:trainsize]
train_tensor

array([[1.        , 0.        , 1.        , 1.        , 1.        ],
       [0.        , 0.66666667, 1.        , 0.8       , 0.403334  ],
       [0.6       , 0.66666667, 0.4       , 0.2       , 0.72      ],
       [0.2       , 0.66666667, 0.8       , 1.        , 0.48      ],
       [0.8       , 0.        , 0.8       , 0.8       , 0.86      ],
       [0.6       , 0.        , 0.6       , 0.6       , 0.68      ],
       [0.4       , 0.        , 0.4       , 0.4       , 0.52      ],
       [0.8       , 0.33333333, 0.2       , 1.        , 0.7       ],
       [0.2       , 0.        , 0.2       , 0.2       , 0.33647   ],
       [0.2       , 0.33333333, 0.4       , 0.        , 0.5049    ],
       [0.        , 0.        , 0.        , 0.        , 0.165306  ],
       [0.6       , 1.        , 0.2       , 0.        , 0.68      ],
       [0.4       , 0.33333333, 0.2       , 0.6       , 0.44      ],
       [0.2       , 0.66666667, 0.        , 0.6       , 0.28      ],
       [0.        , 0.66666667, 0.

In [35]:
valid_tensor = tensor[trainsize: trainsize + validsize]
valid_tensor

array([[1.        , 0.33333333, 0.        , 0.8       , 0.8       ],
       [0.        , 0.33333333, 0.6       , 0.2       , 0.34      ]])

In [36]:
test_tensor = tensor[trainsize + validsize:]
test_tensor

array([[0.6       , 0.33333333, 0.        , 0.4       , 0.54      ],
       [0.4       , 1.        , 0.        , 0.2       , 0.424082  ]])

In [37]:
print(train_tensor.shape, valid_tensor.shape, test_tensor.shape)

(16, 5) (2, 5) (2, 5)


In [38]:
class MyDataset(torch.utils.data.Dataset):
    def __init__(self, tensor, args):
        super(MyDataset, self).__init__()
        self.args = args
        self.data = tensor
    
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        x = self.data[idx][:4]
        y = self.data[idx][4]
        return x, y


In [39]:
train_set = MyDataset(train_tensor, args)
valid_set = MyDataset(valid_tensor, args)
test_set = MyDataset(test_tensor, args)

In [40]:
from torch.utils.data import DataLoader

# 创建数据加载器
batch_size = 1
train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
valid_loader = DataLoader(valid_set, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_set, batch_size=batch_size, shuffle=False)

In [41]:
for train_batch in train_loader:
    x, y = train_batch
for valid_batch in valid_loader:
    x, y = valid_batch

In [42]:
class MLP(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(MLP, self).__init__()
        self.fc1 = torch.nn.Linear(input_dim, hidden_dim // 2)
        self.norm = torch.nn.LayerNorm(hidden_dim // 2, hidden_dim // 2)
        self.relu = torch.nn.ReLU()
        self.fc2 = torch.nn.Linear(hidden_dim // 2, hidden_dim // 4)
        self.norm2 = torch.nn.LayerNorm(hidden_dim // 4, hidden_dim // 4)
        self.relu2 = torch.nn.ReLU()
        self.fc3 = torch.nn.Linear(hidden_dim // 4, output_dim)

    def forward(self, x):
        x = self.fc1(x)
        x = self.norm(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.norm2(x)
        x = self.relu2(x)
        y = self.fc3(x)
        return y.reshape(-1,)
        # return y
        

In [43]:
model = MLP(4, 128, 1)

In [44]:
loss_function = torch.nn.L1Loss()
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

In [45]:
from tqdm import *

In [52]:
for epoch in range(100):
    for train_batch in train_loader:
        x, y = train_batch
        y_pred = model(x)
        loss = loss_function(y_pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    valid_loss = 0.0
    for valid_batch in valid_loader:
        x, y = valid_batch
        y_pred = model(x)
        loss = loss_function(y_pred, y)
        valid_loss += loss.item()
    print(f'epoch: {epoch}, loss: {loss.item() * max_value}')
    
test_loss = 0.0
for test_batch in test_loader:
    x, y = test_batch
    y_pred = model(x)
    loss = loss_function(y_pred, y)
    test_loss += loss.item()
print(f'Test loss: {loss.item() * max_value}')

epoch: 0, loss: 15.839620511483854
epoch: 1, loss: 169.32340516770117
epoch: 2, loss: 188.35464550112897
epoch: 3, loss: 128.2175053791243
epoch: 4, loss: 115.57646823024098
epoch: 5, loss: 160.32460993228332
epoch: 6, loss: 123.27192954030453
epoch: 7, loss: 116.27242311452429
epoch: 8, loss: 44.97026630192275
epoch: 9, loss: 200.644512275176
epoch: 10, loss: 195.8460403277462
epoch: 11, loss: 76.94071036968397
epoch: 12, loss: 175.89218167767595
epoch: 13, loss: 89.7453021299388
epoch: 14, loss: 65.5404057464401
epoch: 15, loss: 136.15657421716887
epoch: 16, loss: 104.26721962537854
epoch: 17, loss: 196.99914338003362
epoch: 18, loss: 137.50218916938812
epoch: 19, loss: 131.88611667486222
epoch: 20, loss: 197.31130094787997
epoch: 21, loss: 154.70326187724564
epoch: 22, loss: 187.25612330826507
epoch: 23, loss: 86.1678475159977
epoch: 24, loss: 120.3102122153027
epoch: 25, loss: 112.11697035392682
epoch: 26, loss: 145.93458069290327
epoch: 27, loss: 138.63793066570597
epoch: 28, loss